alias i3conf='vi ~/.config/i3/config'
alias ffconf='vi ~/.mozilla/firefox/default/chrome/userChrome.css'
alias fishconf='vi ~/.config/fish/config.fish'
alias i3statusconf='vi ~/.i3status.conf'
alias roficonf='vi ~/.config/rofi/config'
alias vimrc='vi ~/.config/nvim/init.vim'

alias update='sudo apt-get update; and sudo apt-get upgrade'
alias vi='nvim'
alias urxvtconf='vi ~/.Xdefaults'
alias ins='sudo apt-get install'
alias mkdir='mkdir -p'
alias g='git'
